# Generated by Django 6.1 on 2026-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
