# Generated by Django 6.1 on 2026-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_stockbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
